import {
  createTheme,
  rem,
  type CSSVariablesResolver,
  type MantineColorsTuple,
} from '@mantine/core';

export const visualTokens = {
  fontUi: 'Inter, "Segoe UI", sans-serif',
  fontData: '"Roboto Mono", Consolas, monospace',
  light: {
    canvas: '#F5F5F5',
    surface: '#FFFFFF',
    surfaceSubtle: '#FAFAFA',
    text: '#171717',
    textMuted: '#525252',
    divider: '#E5E5E5',
    border: '#D4D4D4',
  },
  dark: {
    canvas: '#171717',
    surface: '#262626',
    surfaceSubtle: '#2F2F2F',
    text: '#FAFAFA',
    textMuted: '#D4D4D4',
    divider: '#404040',
    border: '#525252',
  },
} as const;

const institutional: MantineColorsTuple = [
  '#E6FFFB',
  '#CCFBF1',
  '#99F6E4',
  '#5EEAD4',
  '#2DD4BF',
  '#14B8A6',
  '#0D9488',
  '#0F766E',
  '#115E59',
  '#134E4A',
];

export const jbcTheme = createTheme({
  primaryColor: 'jbc',
  colors: { jbc: institutional },
  primaryShade: { light: 7, dark: 3 },
  fontFamily: visualTokens.fontUi,
  fontFamilyMonospace: visualTokens.fontData,
  defaultRadius: rem(8),
  radius: { md: rem(8), lg: rem(12) },
  spacing: {
    xs: rem(8),
    sm: rem(12),
    md: rem(16),
    lg: rem(24),
    xl: rem(32),
  },
  headings: {
    fontFamily: visualTokens.fontUi,
    fontWeight: '650',
    sizes: {
      h1: { fontSize: rem(28), lineHeight: rem(36) },
      h2: { fontSize: rem(22), lineHeight: rem(30) },
      h3: { fontSize: rem(18), lineHeight: rem(26) },
    },
  },
  components: {
    Button: { defaultProps: { h: 44, radius: 'md' } },
    ActionIcon: { defaultProps: { size: 44, radius: 'md' } },
    TextInput: { defaultProps: { size: 'md' } },
    ColorInput: { defaultProps: { size: 'md' } },
    SegmentedControl: { defaultProps: { size: 'md' } },
  },
});

export const semanticColors = {
  success: {
    lightBackground: '#F0FDF4',
    lightText: '#166534',
    darkBackground: '#052E16',
    darkText: '#BBF7D0',
  },
  information: {
    lightBackground: '#EFF6FF',
    lightText: '#1D4ED8',
    darkBackground: '#172554',
    darkText: '#BFDBFE',
  },
  warning: {
    lightBackground: '#FFFBEB',
    lightText: '#92400E',
    darkBackground: '#451A03',
    darkText: '#FDE68A',
  },
  error: {
    lightBackground: '#FEF2F2',
    lightText: '#B91C1C',
    darkBackground: '#450A0A',
    darkText: '#FECACA',
  },
  ai: {
    lightBackground: '#F5F3FF',
    lightText: '#6D28D9',
    darkBackground: '#2E1065',
    darkText: '#DDD6FE',
  },
  apt: {
    lightBackground: '#ECFEFF',
    lightText: '#155E75',
    darkBackground: '#083344',
    darkText: '#A5F3FC',
  },
  siri: {
    lightBackground: '#FFF1F2',
    lightText: '#9F1239',
    darkBackground: '#4C0519',
    darkText: '#FECDD3',
  },
} as const;

export const jbcCssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    '--font-ui': visualTokens.fontUi,
    '--font-data': visualTokens.fontData,
    '--accent-solid': institutional[7],
    '--accent-solid-text': '#FFFFFF',
    '--accent-text-light': institutional[7],
    '--accent-text-dark': institutional[3],
    '--accent-focus-light': institutional[7],
    '--accent-focus-dark': institutional[3],
    '--accent-subtle-light': '#E7F1F0',
    '--accent-subtle-dark': '#213936',
  },
  light: {
    '--color-canvas': visualTokens.light.canvas,
    '--color-surface': visualTokens.light.surface,
    '--color-surface-subtle': visualTokens.light.surfaceSubtle,
    '--color-text': visualTokens.light.text,
    '--color-text-muted': visualTokens.light.textMuted,
    '--color-divider': visualTokens.light.divider,
    '--color-border': visualTokens.light.border,
    '--semantic-success-background': semanticColors.success.lightBackground,
    '--semantic-success-text': semanticColors.success.lightText,
    '--semantic-warning-background': semanticColors.warning.lightBackground,
    '--semantic-warning-text': semanticColors.warning.lightText,
    '--semantic-error-background': semanticColors.error.lightBackground,
    '--semantic-error-text': semanticColors.error.lightText,
    '--semantic-ai-background': semanticColors.ai.lightBackground,
    '--semantic-ai-text': semanticColors.ai.lightText,
    '--semantic-apt-background': semanticColors.apt.lightBackground,
    '--semantic-apt-text': semanticColors.apt.lightText,
    '--semantic-siri-background': semanticColors.siri.lightBackground,
    '--semantic-siri-text': semanticColors.siri.lightText,
  },
  dark: {
    '--color-canvas': visualTokens.dark.canvas,
    '--color-surface': visualTokens.dark.surface,
    '--color-surface-subtle': visualTokens.dark.surfaceSubtle,
    '--color-text': visualTokens.dark.text,
    '--color-text-muted': visualTokens.dark.textMuted,
    '--color-divider': visualTokens.dark.divider,
    '--color-border': visualTokens.dark.border,
    '--semantic-success-background': semanticColors.success.darkBackground,
    '--semantic-success-text': semanticColors.success.darkText,
    '--semantic-warning-background': semanticColors.warning.darkBackground,
    '--semantic-warning-text': semanticColors.warning.darkText,
    '--semantic-error-background': semanticColors.error.darkBackground,
    '--semantic-error-text': semanticColors.error.darkText,
    '--semantic-ai-background': semanticColors.ai.darkBackground,
    '--semantic-ai-text': semanticColors.ai.darkText,
    '--semantic-apt-background': semanticColors.apt.darkBackground,
    '--semantic-apt-text': semanticColors.apt.darkText,
    '--semantic-siri-background': semanticColors.siri.darkBackground,
    '--semantic-siri-text': semanticColors.siri.darkText,
  },
});
